apiVersion: v1
baseDomain: ocp-osp.lab
compute:
- name: worker
  platform: {}
  replicas: 5
controlPlane:
  name: master
  platform: {}
  replicas: 3
metadata:
  name: dzamoran
networking:
  clusterNetworks:
  - cidr: 10.40.0.0/14
    hostSubnetLength: 9
  machineCIDR: 10.30.0.0/16
  serviceCIDR: 172.30.0.0/16
  type: OpenShiftSDN
platform:
  none: {}
pullSecret: '{"auths":{"registry.dzamoran.ocp-osp.lab:5000":{"auth":"************","email":"dzamoran@localdomain.com"}}}'
sshKey: |
  ssh-rsa *******
