---
- name: Ensure openssl is installed
  yum:
    use_backend: yum
    name:
      - openssl
    state: present

- name: Create directory for SSL
  become: true
  file:
    path: "../ssl"
    state: directory
    owner: root
    group: root
    mode: '777'

- name: Create directory for extra files
  become: true
  file:
    path: "../files"
    state: directory
    owner: root
    group: root
    mode: '777'

- name: "Generate private key && Create root CA files"
  become: true
  shell: "{{ item }}"
  args:
    chdir: "../ssl"
  with_items:
  - "openssl genrsa -out rootCA.key 4096"
  - "openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.crt -subj '/'"
