---
- name: Add keypair
  os_keypair:
    cloud: "{{ os_project }}"
    state: "present"
    name: "{{ ospuser }}"
    public_key_file: "{{ ssh_key }}"
- name: TCP Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_project }}"
     security_group: default
     protocol: tcp
     remote_ip_prefix: 0.0.0.0/0
- name: UDP Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_project }}"
     security_group: default
     protocol: udp
     remote_ip_prefix: 0.0.0.0/0
- name: ICMP Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_project }}"
     security_group: default
     protocol: icmp
     remote_ip_prefix: 0.0.0.0/0
- name: SSH Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_project }}"
     security_group: default
     protocol: tcp
     port_range_min: 22
     port_range_max: 22
     remote_ip_prefix: 0.0.0.0/0
- name: Ensure CoreOS image exist
  os_image_facts:
     cloud: "{{ os_project }}"
     image: "{{ coreos_image_name }}"